package br.com.freessh

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.*
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.jcraft.jsch.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.OutputStream
import java.util.Properties

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme(colorScheme=darkColorScheme(primary=Color(0xFF2D8CFF),background=Color(0xFF03080C),surface=Color(0xFF0B151D))){FreeSshApp(ProfileStore(this),HostKeyStore(this))}}}}
data class SshProfile(val name:String,val host:String,val port:Int=22,val user:String,val password:String="",val privateKey:String="",val passphrase:String="",val timeout:Int=15,val keepAlive:Int=30)
class ProfileStore(context:Context){private val prefs=context.getSharedPreferences("profiles",MODE_PRIVATE);fun load():List<SshProfile>=runCatching{val a=JSONArray(prefs.getString("items","[]"));(0 until a.length()).map{i->a.getJSONObject(i).let{o->SshProfile(o.getString("name"),o.getString("host"),o.optInt("port",22),o.getString("user"),o.optString("password"),o.optString("privateKey"),o.optString("passphrase"),o.optInt("timeout",15),o.optInt("keepAlive",30))}}}.getOrDefault(emptyList());fun save(items:List<SshProfile>){val a=JSONArray();items.forEach{p->a.put(JSONObject().apply{put("name",p.name);put("host",p.host);put("port",p.port);put("user",p.user);put("password",p.password);put("privateKey",p.privateKey);put("passphrase",p.passphrase);put("timeout",p.timeout);put("keepAlive",p.keepAlive)})};prefs.edit().putString("items",a.toString()).apply()}}
class HostKeyStore(context:Context){private val prefs=context.getSharedPreferences("trusted_host_keys",MODE_PRIVATE);fun get(h:String,p:Int)=prefs.getString("$h:$p",null);fun trust(h:String,p:Int,k:String)=prefs.edit().putString("$h:$p",k).apply()}
data class HostPrompt(val fingerprint:String,val key:String,val changed:Boolean)
@Composable fun FreeSshApp(store:ProfileStore,keys:HostKeyStore){var ps by remember{mutableStateOf(store.load())};var sel by remember{mutableStateOf<SshProfile?>(null)};if(sel!=null)TerminalScreen(sel!!,keys){sel=null}else ConnectionScreen(ps,{p->ps=ps+p;store.save(ps)},{sel=it},{p->ps=ps-p;store.save(ps)})}
@Composable fun ConnectionScreen(profiles:List<SshProfile>,onSave:(SshProfile)->Unit,onConnect:(SshProfile)->Unit,onDelete:(SshProfile)->Unit){var name by remember{mutableStateOf("")};var host by remember{mutableStateOf("")};var port by remember{mutableStateOf("22")};var user by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var key by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var timeout by remember{mutableStateOf("15")};var keep by remember{mutableStateOf("30")};fun p()=SshProfile(name.ifBlank{"SSH $host"},host,port.toIntOrNull()?:22,user,password,key,pass,timeout.toIntOrNull()?:15,keep.toIntOrNull()?:30);LazyColumn(Modifier.fillMaxSize().background(Color(0xFF071018)).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("FreeSSH",style=MaterialTheme.typography.headlineLarge,color=Color.White);Text("Conexões SSH",color=Color.Gray)};item{OutlinedTextField(name,{name=it},label={Text("Nome do perfil")},modifier=Modifier.fillMaxWidth());OutlinedTextField(host,{host=it},label={Text("IP / hostname")},modifier=Modifier.fillMaxWidth());OutlinedTextField(port,{port=it},label={Text("Porta")},modifier=Modifier.fillMaxWidth());OutlinedTextField(user,{user=it},label={Text("Usuário")},modifier=Modifier.fillMaxWidth());OutlinedTextField(password,{password=it},label={Text("Senha")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth())};item{Text("Avançado");OutlinedTextField(key,{key=it},label={Text("Chave privada")},modifier=Modifier.fillMaxWidth());OutlinedTextField(pass,{pass=it},label={Text("Passphrase")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Row{OutlinedTextField(timeout,{timeout=it},label={Text("Timeout")},modifier=Modifier.weight(1f));Spacer(Modifier.width(8.dp));OutlinedTextField(keep,{keep=it},label={Text("Keepalive")},modifier=Modifier.weight(1f))}};item{Row{Button({if(host.isNotBlank()&&user.isNotBlank())onConnect(p())}){Text("Conectar")};Spacer(Modifier.width(8.dp));OutlinedButton({if(host.isNotBlank()&&user.isNotBlank())onSave(p())}){Text("Salvar")}};Text("Perfis salvos",style=MaterialTheme.typography.titleLarge)};items(profiles){p->Card{Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(p.name);Text("${p.user}@${p.host}:${p.port}",color=Color.Gray)};Button({onConnect(p)}){Text("Abrir")};IconButton({onDelete(p)}){Icon(Icons.Default.Delete,"Excluir")}}}}}}

private val ansiRegex=Regex("\\u001B\\[[0-?]*[ -/]*[@-~]")
private fun ansiText(raw:String):AnnotatedString{val b=AnnotatedString.Builder();var pos=0;var color=Color(0xFFE6E6E6);ansiRegex.findAll(raw).forEach{m->if(m.range.first>pos)b.withStyle(SpanStyle(color=color)){append(raw.substring(pos,m.range.first))};val code=m.value;if(code.endsWith("m")){val nums=code.removePrefix("\u001B[").removeSuffix("m").split(';').mapNotNull{it.toIntOrNull()};if(nums.isEmpty()||0 in nums)color=Color(0xFFE6E6E6);nums.forEach{n->color=when(n){30->Color(0xFF555555);31,91->Color(0xFFFF5F56);32,92->Color(0xFF64E572);33,93->Color(0xFFFFD75F);34,94->Color(0xFF4C9AFF);35,95->Color(0xFFD875FF);36,96->Color(0xFF55DDE0);37,97->Color.White;else->color}}};pos=m.range.last+1};if(pos<raw.length)b.withStyle(SpanStyle(color=color)){append(raw.substring(pos))};return b.toAnnotatedString()}

@Composable fun TerminalScreen(p:SshProfile,keys:HostKeyStore,onBack:()->Unit){var output by remember{mutableStateOf("")};var cmd by remember{mutableStateOf("")};var connected by remember{mutableStateOf(false)};var session by remember{mutableStateOf<Session?>(null)};var channel by remember{mutableStateOf<ChannelShell?>(null)};var stdin by remember{mutableStateOf<OutputStream?>(null)};var prompt by remember{mutableStateOf<HostPrompt?>(null)};var decision by remember{mutableStateOf<Boolean?>(null)};val scroll=rememberScrollState();fun write(s:String){val w=stdin?:return;kotlin.concurrent.thread{runCatching{w.write(s.toByteArray());w.flush()}}};fun send(){if(cmd.isNotEmpty()){write(cmd+"\n");cmd=""}};fun close(){runCatching{channel?.disconnect()};runCatching{session?.disconnect()}}
 if(prompt!=null)AlertDialog(onDismissRequest={decision=false},title={Text(if(prompt!!.changed)"Chave do servidor mudou" else "Confiar neste servidor?")},text={Column{Text("${p.host}:${p.port}");Spacer(Modifier.height(8.dp));Text(prompt!!.fingerprint,fontFamily=FontFamily.Monospace);if(prompt!!.changed)Text("\nA chave é diferente da salva. Confirme apenas se reconhecer a alteração.")}},confirmButton={Button({decision=true}){Text("Confiar")}},dismissButton={TextButton({decision=false}){Text("Cancelar")}})
 LaunchedEffect(p){withContext(Dispatchers.IO){runCatching{val j=JSch();if(p.privateKey.isNotBlank())j.addIdentity("profile",p.privateKey.toByteArray(),null,p.passphrase.ifBlank{null}?.toByteArray());val s=j.getSession(p.user,p.host,p.port);if(p.password.isNotBlank())s.setPassword(p.password);s.timeout=p.timeout*1000;s.serverAliveInterval=p.keepAlive*1000;s.setConfig(Properties().apply{put("StrictHostKeyChecking","ask")});s.setUserInfo(object:UserInfo{override fun getPassword()=p.password;override fun getPassphrase()=p.passphrase;override fun promptPassword(x:String)=p.password.isNotBlank();override fun promptPassphrase(x:String)=p.passphrase.isNotBlank();override fun showMessage(x:String){};override fun promptYesNo(x:String):Boolean{val hk=s.hostKey?:return false;val cur=hk.key;val saved=keys.get(p.host,p.port);runOnUiThread{decision=null;prompt=HostPrompt(hk.getFingerPrint(j),cur,saved!=null&&saved!=cur)};while(decision==null)Thread.sleep(100);val ok=decision==true;if(ok)keys.trust(p.host,p.port,cur);runOnUiThread{prompt=null};return ok}});keys.get(p.host,p.port)?.let{j.hostKeyRepository.add(HostKey(p.host,java.util.Base64.getDecoder().decode(it)),null)};s.connect();session=s;val sh=s.openChannel("shell") as ChannelShell;sh.setPty(true);sh.setPtyType("xterm-256color",120,40,1080,720);stdin=sh.outputStream;val input=sh.inputStream;sh.connect();channel=sh;runOnUiThread{connected=true};val buf=ByteArray(8192);while(sh.isConnected){val n=input.read(buf);if(n<0)break;if(n>0)runOnUiThread{output+=String(buf,0,n)}}}.onFailure{runOnUiThread{output+="\nErro: ${it.message}\n"}};runOnUiThread{connected=false}}}
 DisposableEffect(Unit){onDispose{close()}};LaunchedEffect(output){scroll.animateScrollTo(scroll.maxValue)}
 Column(Modifier.fillMaxSize().background(Color(0xFF020609))){Row(Modifier.fillMaxWidth().background(Color(0xFF0B1821)).padding(12.dp),verticalAlignment=Alignment.CenterVertically){IconButton({close();onBack()}){Icon(Icons.Default.ArrowBack,"Voltar",tint=Color.White)};Column(Modifier.weight(1f)){Text(p.name,color=Color.White,style=MaterialTheme.typography.titleLarge);Row(verticalAlignment=Alignment.CenterVertically){Text("●",color=if(connected)Color(0xFF38E65C) else Color(0xFFFFC857),fontSize=13.sp);Spacer(Modifier.width(6.dp));Text(if(connected)"Conectado" else "Conectando...",color=Color.LightGray)}};IconButton({}){Icon(Icons.Default.Add,"Novo",tint=Color.White)};IconButton({}){Icon(Icons.Default.Keyboard,"Teclado",tint=Color.White)}}
  Text(ansiText(output),fontFamily=FontFamily.Monospace,fontSize=14.sp,lineHeight=19.sp,modifier=Modifier.weight(1f).fillMaxWidth().padding(12.dp).verticalScroll(scroll))
  Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).background(Color(0xFF061018)).padding(horizontal=6.dp,vertical=5.dp),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("ESC" to "\u001b","CTRL+C" to "\u0003","TAB" to "\t","↑" to "\u001b[A","↓" to "\u001b[B","←" to "\u001b[D","→" to "\u001b[C","-" to "-","/" to "/","|" to "|").forEach{(label,value)->Button(onClick={write(value)},colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF14232E)),contentPadding=PaddingValues(horizontal=15.dp,vertical=8.dp)){Text(label,color=Color.White)}}}
  Row(Modifier.fillMaxWidth().background(Color(0xFF061018)).padding(7.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(cmd,{cmd=it},placeholder={Text("Digite um comando...")},singleLine=true,keyboardOptions=KeyboardOptions(imeAction=ImeAction.Send),keyboardActions=KeyboardActions(onSend={send()},onDone={send()}),modifier=Modifier.weight(1f),colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Color.White,unfocusedTextColor=Color.White));Spacer(Modifier.width(7.dp));Button(onClick={send},modifier=Modifier.height(56.dp)){Text("ENVIAR")}}
  Row(Modifier.fillMaxWidth().background(Color(0xFF0A151D)).padding(vertical=8.dp),horizontalArrangement=Arrangement.SpaceAround){BottomItem("▣","Terminal",true);BottomItem("□","SFTP",false);BottomItem("→","Portas",false);BottomItem("▤","Logs",false)}
 }}
@Composable private fun BottomItem(icon:String,label:String,active:Boolean){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(icon,color=if(active)Color(0xFF2D8CFF) else Color.Gray,fontSize=22.sp);Text(label,color=if(active)Color(0xFF2D8CFF) else Color.Gray,fontSize=12.sp)}}
